In [2]:
import numpy as np

In [6]:
arr1D = np.array([1, 2, 3])
print(arr1D)

arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2D)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [ ]:
py_list = [1, 2, 3]
print("Multiplying python list: ", py_list * 2)

np_array = np.array([1, 2,3]);
print("Multipyling numpy array: ", np_array * 2)

Multiplying python list:  [1, 2, 3, 1, 2, 3]
Multipyling numpy array:  [2 4 6]


In [8]:
import time 
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("Python list operation time", (time.time() - start))

start = time.time();
np_array = np.arange(1000000) * 2
print("Numpy array operation time", (time.time() - start))

Python list operation time 0.11687564849853516
Numpy array operation time 0.006398916244506836


In [16]:
zeros = np.zeros((3, 4))
print("Zeros:\n", zeros)

ones = np.ones((3, 4))
print("\nOnes:\n", ones)

full = np.full((3, 4), 7)
print("\nFull:\n", full)

random = np.random.random((3, 5))
print("\nRandom:\n", random)

sequence = np.arange(0, 11, 2)
print("\nSequence:\n", sequence)

Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Full:
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]

Random:
 [[0.71017265 0.20200563 0.60259891 0.57309947 0.32829071]
 [0.03910796 0.18250211 0.62531575 0.7041098  0.64317494]
 [0.07656849 0.44343663 0.48079113 0.24405809 0.80271327]]

Sequence:
 [ 0  2  4  6  8 10]


In [20]:
vector = np.array([1, 2, 3])
print("\nVector:\n", vector)

matric = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nMatric:\n", matric)

tensor = np.array([[[1,2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print("\nTensor:\n", tensor)


Vector:
 [1 2 3]

Matric:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Tensor:
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [27]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print("Shape", arr.shape)
print("Dimension", arr.ndim)
print("Size", arr.size)
print("D Type: ", arr.dtype)

Shape (2, 3)
Dimension 2
Size 6
D Type:  int64


In [33]:
arr = np.arange(12)
print("Original: ", arr)

reshaped = arr.reshape((3, 4))
print("Reshaped: ", reshaped)

flattended = reshaped.flatten()
print("Flatten: ", flattended)

transposed = reshaped.transpose()
print("Transpose: ", transposed)

Original:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flatten:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
