In [2]:
import numpy as np

In [3]:
arr = np.arange(1, 11, 1)
print("Base Array: ", arr)
print("Basic slicing: ", arr[2:7])  # can be done with step as well 
print("Negative Indexing: ", arr[-3]) # return third from last

Base Array:  [ 1  2  3  4  5  6  7  8  9 10]
Basic slicing:  [3 4 5 6 7]
Negative Indexing:  8


In [8]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Sepecific element: ", arr2d[2][2])
print("Entire row: ", arr2d[1, :])
print("Entire column: ", arr2d[:, 0])

Sepecific element:  9
Entire row:  [4 5 6]
Entire column:  [1 4 7]


In [9]:
arr = np.array([3,25,43,26,3,73,476,4])
print("sorted array: ", np.sort(arr))

sorted array:  [  3   3   4  25  26  43  73 476]


In [ ]:
arr2d_unsorted = np.array([[2, 1], [4, 5], [8, 4]])
print("Sorted 2d: ", np.sort(arr2d_unsorted, axis=0)) # axis = 1 sorts row wise and axis = 0 sorts column wise

Sorted 2d:  [[2 1]
 [4 4]
 [8 5]]


In [21]:
arr = np.arange(1, 11)
even = arr[arr % 2 == 0] # selects even number from the array
print(even)

[ 2  4  6  8 10]


In [ ]:
mask = arr > 5
print(arr[mask]) # this is mask hold expression

[ 6  7  8  9 10]


In [26]:
indices = [1, 3, 5]
print(arr[indices])

where = np.where(arr > 5) #fancy way of indexing and filtering
print(arr[where])

[2 4 6]
[ 6  7  8  9 10]


In [29]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.concatenate((arr1, arr2))
print(arr3)
print("Compalibility shape: ", arr1.shape == arr2.shape)

[1 2 3 4 5 6]
Compalibility shape:  True


In [ ]:
org = np.array([[1, 2], [3, 4]])
new = np.array([5, 6]) 
# print(np.vstack((org, new)))  # vstack adds a new row

new = np.array([[5], [6]]) 
print(np.hstack((org, new)))  # hstack adds a new col

[[1 2 5]
 [3 4 6]]


In [36]:
arr = np.array([1, 2, 3, 4, 5, 6])
delete = np.delete(arr, 2)
print(delete)

[1 2 4 5 6]
